## 文档参考
[Pad API](https://numpy.org/devdocs/reference/generated/numpy.pad.html#numpy.pad)  
[Numpy学习——数组填充np.pad()函数的应用](https://blog.csdn.net/zenghaitao0128/article/details/78713663)

## 参数介绍
> ndarray = numpy.pad(array, pad_width, mode, **kwargs)
* array为要填补的数组
* pad_width是在各维度的各个方向上想要填补的长度,如（（1，2），（2，2）），表示在第一个维度上水平方向上padding=1,垂直方向上padding=2,在第二个维度上水平方向上padding=2,垂直方向上padding=2。如果直接输入一个整数，则说明各个维度和各个方向所填补的长度都一样。
* mode为填补类型，即怎样去填补，有“constant”，“edge”等模式，如果为constant模式，就得指定填补的值，如果不指定，则默认填充0。 
* ndarray为填充好的返回值。

##填充方式
- 'constant’——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0

- ‘edge’——表示用边缘值填充

- ‘linear_ramp’——表示用边缘递减的方式填充

- ‘maximum’——表示最大值填充

- ‘mean’——表示均值填充

- ‘median’——表示中位数填充

- ‘minimum’——表示最小值填充

- ‘reflect’——表示对称填充

- ‘symmetric’——表示对称填充

- ‘wrap’——表示用原数组后面的值填充前面，前面的值填充后面



In [15]:
import numpy as np


In [16]:
a = [1,2,3,4,5]
# print(a.shape)
np.pad(a, (2,0), 'constant', constant_values=(4))

array([4, 4, 1, 2, 3, 4, 5])

In [17]:
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [18]:
np.pad(a, (2, 3), 'edge')

array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

In [19]:
np.pad(a, (2, 3), 'linear_ramp', end_values=(5, -4))

array([ 5,  3,  1,  2,  3,  4,  5,  2, -1, -4])

In [20]:
np.pad(a, (2,), 'maximum')

array([5, 5, 1, 2, 3, 4, 5, 5, 5])

In [21]:
np.pad(a, (2,), 'mean')

array([3, 3, 1, 2, 3, 4, 5, 3, 3])

In [22]:
np.pad(a, (2,), 'median')

array([3, 3, 1, 2, 3, 4, 5, 3, 3])

## 轴镜像翻转

In [23]:
np.pad(a, (2, 3), 'reflect')

array([3, 2, 1, 2, 3, 4, 5, 4, 3, 2])

In [24]:
np.pad(a, (2, 3), 'reflect', reflect_type='odd')

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [8]:
m =np.random.randint(1,10,(3,5,6))
m

array([[[6, 4, 2, 5, 6, 6],
        [8, 4, 7, 4, 9, 8],
        [7, 6, 1, 8, 6, 3],
        [3, 4, 1, 3, 4, 8],
        [5, 9, 4, 5, 9, 7]],

       [[4, 4, 1, 7, 5, 2],
        [6, 4, 7, 6, 2, 5],
        [5, 1, 3, 4, 7, 3],
        [9, 4, 9, 5, 4, 7],
        [6, 3, 1, 8, 5, 4]],

       [[5, 9, 8, 5, 3, 3],
        [5, 6, 3, 4, 7, 4],
        [5, 1, 4, 6, 8, 7],
        [1, 5, 3, 9, 2, 9],
        [2, 2, 6, 2, 4, 1]]])

In [9]:
k = np.pad(m, ((0,1),(0,1),(0,1)), 'constant', constant_values=(0,-1))
k

array([[[ 6,  4,  2,  5,  6,  6, -1],
        [ 8,  4,  7,  4,  9,  8, -1],
        [ 7,  6,  1,  8,  6,  3, -1],
        [ 3,  4,  1,  3,  4,  8, -1],
        [ 5,  9,  4,  5,  9,  7, -1],
        [-1, -1, -1, -1, -1, -1, -1]],

       [[ 4,  4,  1,  7,  5,  2, -1],
        [ 6,  4,  7,  6,  2,  5, -1],
        [ 5,  1,  3,  4,  7,  3, -1],
        [ 9,  4,  9,  5,  4,  7, -1],
        [ 6,  3,  1,  8,  5,  4, -1],
        [-1, -1, -1, -1, -1, -1, -1]],

       [[ 5,  9,  8,  5,  3,  3, -1],
        [ 5,  6,  3,  4,  7,  4, -1],
        [ 5,  1,  4,  6,  8,  7, -1],
        [ 1,  5,  3,  9,  2,  9, -1],
        [ 2,  2,  6,  2,  4,  1, -1],
        [-1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1]]])

In [13]:
B = np.arange(1,5).reshape(1,2,2)  #原始输入数组
B

array([[[1, 2],
        [3, 4]]])

In [ ]:
np.pad(B,())

## torch.nn.functional.pad
https://pytorch.org/docs/stable/generated/torch.nn.functional.pad.html   


从最后一个维度开始向前填充
1维度(pading_left,pading_right)  
2维度(padding_left,padding_right, padding_top, padding_bottom,padding_top,padding_bottom)  
常量填充("constant")可用于任意尺寸。     
复制填充('replicate')用于填充5D输入张量的最后3维，或4D输入张量的最后2维，或3D输入张量的最后1维。  
反射填充('reflect')仅用于填充4D输入张量的最后2维，或3D输入张量的最后1维。  
参考 ConstantPad2d torch.nn。ReflectionPad2d, torch.nn。ReplicationPad2d 例子，了解他们是怎么填充的  

In [10]:
import torch
from torch.nn import functional as F

a = torch.randn([2,3,4,5])  # torch.Size([2, 3, 4, 5])
padding = (
    1,2,   # 前面填充1个单位，后面填充两个单位，输入的最后一个维度则增加1+2个单位，成为8
    2,3,
    3,4
)
print(a.shape)
b = F.pad(a, padding)
print(b.shape)  # torch.Size([2, 10, 9, 8])  


torch.Size([2, 3, 4, 5])
torch.Size([2, 10, 9, 8])


In [12]:
c = F.pad(a, (1,2,3,4),'replicate')
print(c.shape)  # torch.Size([2, 10, 9, 8])  

torch.Size([2, 3, 11, 8])


In [11]:
import numpy as np
a = np.zeros((2,3),np.float32)
b = np.expand_dims(a,axis=0)
b.shape


(1, 2, 3)