In [9]:
import numpy as np
import torch

In [10]:
a= np.array([[1, 1, 1, 3, 3, 3, 2, 2, 2],
          [1, 1, 1, 3, 3, 3, 2, 2, 2],
          [1, 1, 1, 3, 3, 3, 2, 2, 2],
          [1, 1, 1, 3, 3, 3, 2, 2, 2]
          ])
print(a,a.shape,a.dtype)

a_x = torch.from_numpy(a)
print(a_x.shape,a_x.dtype)

[[1 1 1 3 3 3 2 2 2]
 [1 1 1 3 3 3 2 2 2]
 [1 1 1 3 3 3 2 2 2]
 [1 1 1 3 3 3 2 2 2]] (4, 9) int32
torch.Size([4, 9]) torch.int32


In [12]:
max_ind = np.unravel_index(torch.argmax(a_x).item(), a_x.shape)
print(max_ind)

(0, 3)
